// Top-level build file where you can add configuration options common to all sub-projects/modules.


buildscript {
    // modern configuration: AndroidX project, no Kotlin support plugin
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // updated to latest stable Android Gradle Plugin (>=9.0.0 as of 2026)
        classpath 'com.android.tools.build:gradle:9.0.0'
        // include Kotlin gradle plugin latest stable so we can set JVM target 25
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.10.0'
        // other classpaths (lint, crashlytics etc.) can be added here if needed
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven {
            url = uri("https://maven.google.com")
        }
        google()

    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
